
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KriShaivi
 */
public class AddCartPanel extends javax.swing.JPanel {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement preparedStatement = null;
    /**
     * Creates new form AddCartPanel
     */
    static{
        sql = "SELECT * FROM cart ORDER BY cart_id ASC";
    }
    public AddCartPanel() {
        initComponents();
        conn = MySqlConnect.connectDb();
        lblCartId.setVisible(false);
        txtCartId.setVisible(false);
        fillCustomerCmb();
        fillProductCmb();
        updatejCartTableData();
    }
    
    private void fillCustomerCmb(){
        try{
            String sql = "SELECT cust_name FROM customer";
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            cmbCustName.removeAllItems();
            while(rs.next()){
                cmbCustName.addItem(rs.getString("cust_name"));
            }
        }catch(Exception e){
        }
    }
    
    private void fillProductCmb(){
        try{
            String sql = "SELECT prod_name FROM product";
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            cmbProdName.removeAllItems();
            while(rs.next()){
                cmbProdName.addItem(rs.getString("prod_name"));
            }
        }catch(Exception e){
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCartData = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblProdName = new javax.swing.JLabel();
        lblCustName = new javax.swing.JLabel();
        lblCartId = new javax.swing.JLabel();
        txtCartId = new javax.swing.JTextField();
        cmbCustName = new javax.swing.JComboBox<>();
        cmbProdName = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1119, 500));

        jPanel1.setBackground(new java.awt.Color(12, 124, 89));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 99, Short.MAX_VALUE)
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableCartData.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jTableCartData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCartData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCartDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCartData);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblProdName.setBackground(new java.awt.Color(194, 1, 20));
        lblProdName.setFont(new java.awt.Font("Gill Sans MT", 0, 30)); // NOI18N
        lblProdName.setForeground(new java.awt.Color(12, 124, 89));
        lblProdName.setText("Product");

        lblCustName.setBackground(new java.awt.Color(194, 1, 20));
        lblCustName.setFont(new java.awt.Font("Gill Sans MT", 0, 30)); // NOI18N
        lblCustName.setForeground(new java.awt.Color(12, 124, 89));
        lblCustName.setText("Customer");

        lblCartId.setText("cart_id");

        txtCartId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCartIdActionPerformed(evt);
            }
        });

        cmbCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCustNameActionPerformed(evt);
            }
        });

        cmbProdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProdNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbProdName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbCustName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCustName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProdName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCartId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCartId))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCustName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblProdName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(313, 313, 313)
                .addComponent(lblCartId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCartId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void updatejCartTableData(){
        String sql = "Select cust_name, prod_name from customer INNER JOIN product on cust_id=prod_id";

        try{
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            jTableCartData.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
        }
        finally{
            try{
            rs.close();
            preparedStatement.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());    
            }
        }
    }
    private void txtCartIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCartIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCartIdActionPerformed

    private void cmbCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCustNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbCustNameActionPerformed

    private void cmbProdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProdNameActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cmbProdNameActionPerformed

    private void jTableCartDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCartDataMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTableCartDataMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCustName;
    private javax.swing.JComboBox<String> cmbProdName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCartData;
    private javax.swing.JLabel lblCartId;
    private javax.swing.JLabel lblCustName;
    private javax.swing.JLabel lblProdName;
    private javax.swing.JTextField txtCartId;
    // End of variables declaration//GEN-END:variables
    static final String sql;
}
