
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.coobird.thumbnailator.Thumbnails;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KriShaivi
 */
public class AddCustomerPanel extends javax.swing.JPanel {
    Connection conn = null;
    PreparedStatement preparedStatement = null;
    ResultSet rs = null;
    /**
     * Creates new form AddCustomerPanel
     */
    static{
        sql = "SELECT * FROM customer ORDER BY cust_name ASC";
    }
    public AddCustomerPanel() {
        initComponents();
        conn = MySqlConnect.connectDb();
        lblSignUpCustId.setVisible(false);
        txtSignUpCustId.setVisible(false);
        updatejCustomerTableData(AddCustomerPanel.sql);
    }
    
    private void updatejCustomerTableData(String sql){
        try{
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            jCustomerTableData.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
        }
        finally{
            try{
            rs.close();
            preparedStatement.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());    
            }
        }
    }    
    private void clear(){
            txtSignUpUsername.setText("");
            txtSignUpPassword.setText("");
            txtSignUpContactNo.setText("");
            txtSignUpAddress.setText("");
            txtSignUpEmailId.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblSignUpContactNo = new javax.swing.JLabel();
        lblSignUpPassword = new javax.swing.JLabel();
        lblSignUpUsername = new javax.swing.JLabel();
        lblSignUpEmailId = new javax.swing.JLabel();
        lblSignUpAddress = new javax.swing.JLabel();
        txtSignUpUsername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtSignUpContactNo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtSignUpEmailId = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtSignUpAddress = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtSignUpPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        lblSignUpCustId = new javax.swing.JLabel();
        txtSignUpCustId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCustomerTableData = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        jButton4.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1119, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblSignUpContactNo.setBackground(new java.awt.Color(23, 23, 56));
        lblSignUpContactNo.setFont(new java.awt.Font("Gill Sans MT", 0, 30)); // NOI18N
        lblSignUpContactNo.setText("Contact No.");

        lblSignUpPassword.setBackground(new java.awt.Color(23, 23, 56));
        lblSignUpPassword.setFont(new java.awt.Font("Gill Sans MT", 0, 30)); // NOI18N
        lblSignUpPassword.setText("Password");

        lblSignUpUsername.setBackground(new java.awt.Color(23, 23, 56));
        lblSignUpUsername.setFont(new java.awt.Font("Gill Sans MT", 0, 30)); // NOI18N
        lblSignUpUsername.setText("Username");

        lblSignUpEmailId.setBackground(new java.awt.Color(23, 23, 56));
        lblSignUpEmailId.setFont(new java.awt.Font("Gill Sans MT", 0, 30)); // NOI18N
        lblSignUpEmailId.setText("Email-Id");

        lblSignUpAddress.setBackground(new java.awt.Color(23, 23, 56));
        lblSignUpAddress.setFont(new java.awt.Font("Gill Sans MT", 0, 30)); // NOI18N
        lblSignUpAddress.setText("Address");

        txtSignUpUsername.setFont(new java.awt.Font("Gill Sans MT", 0, 25)); // NOI18N
        txtSignUpUsername.setBorder(null);
        txtSignUpUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignUpUsernameActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(23, 23, 56));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        txtSignUpContactNo.setFont(new java.awt.Font("Gill Sans MT", 0, 25)); // NOI18N
        txtSignUpContactNo.setBorder(null);
        txtSignUpContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignUpContactNoActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(23, 23, 56));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        txtSignUpEmailId.setFont(new java.awt.Font("Gill Sans MT", 0, 25)); // NOI18N
        txtSignUpEmailId.setBorder(null);
        txtSignUpEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignUpEmailIdActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(23, 23, 56));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        txtSignUpAddress.setFont(new java.awt.Font("Gill Sans MT", 0, 25)); // NOI18N
        txtSignUpAddress.setBorder(null);
        txtSignUpAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignUpAddressActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(23, 23, 56));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        txtSignUpPassword.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        txtSignUpPassword.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(23, 23, 56));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        lblSignUpCustId.setText("cust_id");

        txtSignUpCustId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSignUpCustIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSignUpCustId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSignUpCustId))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblSignUpContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                    .addComponent(lblSignUpUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSignUpPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSignUpEmailId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSignUpAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSignUpUsername)
                    .addComponent(jSeparator1)
                    .addComponent(txtSignUpContactNo)
                    .addComponent(jSeparator3)
                    .addComponent(txtSignUpEmailId)
                    .addComponent(jSeparator4)
                    .addComponent(txtSignUpAddress)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator2)
                    .addComponent(txtSignUpPassword))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSignUpUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSignUpUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblSignUpPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSignUpPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblSignUpContactNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSignUpContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSignUpEmailId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSignUpEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSignUpAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSignUpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSignUpCustId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSignUpCustId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jCustomerTableData.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jCustomerTableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jCustomerTableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCustomerTableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jCustomerTableData);

        jPanel1.setBackground(new java.awt.Color(23, 23, 56));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/short-broom.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(978, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSignUpUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignUpUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignUpUsernameActionPerformed

    private void txtSignUpContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignUpContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignUpContactNoActionPerformed

    private void txtSignUpEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignUpEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignUpEmailIdActionPerformed

    private void txtSignUpAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignUpAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignUpAddressActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE customer SET cust_name = ?,cust_pass = ?, contact_no = ?, cust_address = ?,"
            + "email_id = ? WHERE cust_id = ?";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, txtSignUpUsername.getText());
            preparedStatement.setString(2, txtSignUpPassword.getText());
            preparedStatement.setString(3, txtSignUpContactNo.getText());
            preparedStatement.setString(4, txtSignUpAddress.getText());
            preparedStatement.setString(5, txtSignUpEmailId.getText());
            preparedStatement.setInt(6, Integer.parseInt(txtSignUpCustId.getText()));
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null,"Record Updated Successfully");
            updatejCustomerTableData(AddCustomerPanel.sql);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtSignUpCustIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSignUpCustIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSignUpCustIdActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO customer(cust_name,cust_pass,contact_no,cust_address,email_id)"
            + "VALUES(?, ?, ?, ?, ?)";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, txtSignUpUsername.getText());
            preparedStatement.setString(2, txtSignUpPassword.getText());
            preparedStatement.setString(3, txtSignUpContactNo.getText());
            preparedStatement.setString(4, txtSignUpAddress.getText());
            preparedStatement.setString(5, txtSignUpEmailId.getText());
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null,"Signup Successful");
            updatejCustomerTableData(AddCustomerPanel.sql);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue"+e.getMessage());
        }
        //        finally{
            //            txtSignUpUsername.setText("");
            //            txtSignUpPassword.setText("");
            //            txtSignUpContactNo.setText("");
            //            txtSignUpAddress.setText("");
            //            txtSignUpEmailId.setText("");
            //        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jCustomerTableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCustomerTableDataMouseClicked
        // TODO add your handling code here:
        int selectedRow = jCustomerTableData.getSelectedRow();
        String selectedCId = jCustomerTableData.getModel().getValueAt(selectedRow, 0).toString();
        try{
            String sql = "SELECT * FROM customer WHERE cust_id = " + selectedCId;
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            if(rs.next()){
                txtSignUpCustId.setText(rs.getString("cust_id"));
                txtSignUpUsername.setText(rs.getString("cust_name"));
                txtSignUpPassword.setText(rs.getString("cust_pass"));
                txtSignUpContactNo.setText(rs.getString("contact_no"));
                txtSignUpAddress.setText(rs.getString("cust_address"));
                txtSignUpEmailId.setText(rs.getString("email_id"));
            }
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_jCustomerTableDataMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if("".equals(txtSignUpCustId.getText())){
            JOptionPane.showMessageDialog(null,"Please select record to delete");
        }
        else{
            int btn = JOptionPane.showConfirmDialog(null,"Are you sure you wanna delete the record?","Delete",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(btn == JOptionPane.YES_OPTION){
                try{
                    String sql = "DELETE FROM customer WHERE cust_id = ?";
                    preparedStatement = conn.prepareStatement(sql);
                    preparedStatement.setInt(1, Integer.parseInt(txtSignUpCustId.getText()));
                    preparedStatement.execute();
                    JOptionPane.showMessageDialog(null,"Record Deleted Successfully!");
                    updatejCustomerTableData(AddCustomerPanel.sql);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
                }
                finally{
                    try{
                        preparedStatement.close();
                    }
                    catch(Exception e){}
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton4;
    private javax.swing.JTable jCustomerTableData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblSignUpAddress;
    private javax.swing.JLabel lblSignUpContactNo;
    private javax.swing.JLabel lblSignUpCustId;
    private javax.swing.JLabel lblSignUpEmailId;
    private javax.swing.JLabel lblSignUpPassword;
    private javax.swing.JLabel lblSignUpUsername;
    private javax.swing.JTextField txtSignUpAddress;
    private javax.swing.JTextField txtSignUpContactNo;
    private javax.swing.JTextField txtSignUpCustId;
    private javax.swing.JTextField txtSignUpEmailId;
    private javax.swing.JPasswordField txtSignUpPassword;
    private javax.swing.JTextField txtSignUpUsername;
    // End of variables declaration//GEN-END:variables
    static final String sql;
}
