import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KriShaivi
 */
public class AddProductPanel extends javax.swing.JPanel {
    Connection conn = null;
    PreparedStatement preparedStatement = null;
    ResultSet rs = null;
    /**
     * Creates new form AddProductPanel
     */
        static{
        sql = "SELECT * FROM product ORDER BY prod_id ASC";
    }
    public AddProductPanel() {
        initComponents();
        conn = MySqlConnect.connectDb();
        lblProdId.setVisible(false);
        txtProdId.setVisible(false);
        updatejProductTableData(AddProductPanel.sql);
    }
    private void updatejProductTableData(String sql){
        try{
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            jTableProductData.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
        }
        finally{
            try{
            rs.close();
            preparedStatement.close();
            }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());    
            }
        }
    }    
    private void clear(){
        txtProdId.setText("");
        txtProdName.setText("");
        txtProdPrice.setText("");
        txtProdQuantity.setText("");
        txtProdBrand.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblProdQuantity = new javax.swing.JLabel();
        lblProdPrice = new javax.swing.JLabel();
        lblProdName = new javax.swing.JLabel();
        lblProdType = new javax.swing.JLabel();
        lblProdBrand = new javax.swing.JLabel();
        txtProdPrice = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtProdQuantity = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtProdBrand = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblProdId = new javax.swing.JLabel();
        txtProdId = new javax.swing.JTextField();
        rbtnMobile = new javax.swing.JRadioButton();
        rbtnAccessories = new javax.swing.JRadioButton();
        txtProdName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductData = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1119, 500));

        jPanel1.setBackground(new java.awt.Color(194, 1, 20));

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh.png"))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/short-broom.png"))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(726, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(978, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblProdQuantity.setBackground(new java.awt.Color(194, 1, 20));
        lblProdQuantity.setFont(new java.awt.Font("Gill Sans MT", 0, 30)); // NOI18N
        lblProdQuantity.setForeground(new java.awt.Color(194, 1, 20));
        lblProdQuantity.setText("Quantity");

        lblProdPrice.setBackground(new java.awt.Color(194, 1, 20));
        lblProdPrice.setFont(new java.awt.Font("Gill Sans MT", 0, 30)); // NOI18N
        lblProdPrice.setForeground(new java.awt.Color(194, 1, 20));
        lblProdPrice.setText("Price");

        lblProdName.setBackground(new java.awt.Color(194, 1, 20));
        lblProdName.setFont(new java.awt.Font("Gill Sans MT", 0, 30)); // NOI18N
        lblProdName.setForeground(new java.awt.Color(194, 1, 20));
        lblProdName.setText("Name");

        lblProdType.setBackground(new java.awt.Color(194, 1, 20));
        lblProdType.setFont(new java.awt.Font("Gill Sans MT", 0, 30)); // NOI18N
        lblProdType.setForeground(new java.awt.Color(194, 1, 20));
        lblProdType.setText("Type");

        lblProdBrand.setBackground(new java.awt.Color(194, 1, 20));
        lblProdBrand.setFont(new java.awt.Font("Gill Sans MT", 0, 30)); // NOI18N
        lblProdBrand.setForeground(new java.awt.Color(194, 1, 20));
        lblProdBrand.setText("Brand");

        txtProdPrice.setFont(new java.awt.Font("Gill Sans MT", 0, 25)); // NOI18N
        txtProdPrice.setBorder(null);
        txtProdPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdPriceActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(194, 1, 20));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        txtProdQuantity.setFont(new java.awt.Font("Gill Sans MT", 0, 25)); // NOI18N
        txtProdQuantity.setBorder(null);
        txtProdQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdQuantityActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(194, 1, 20));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        txtProdBrand.setFont(new java.awt.Font("Gill Sans MT", 0, 25)); // NOI18N
        txtProdBrand.setBorder(null);
        txtProdBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdBrandActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(194, 1, 20));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(194, 1, 20));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        lblProdId.setText("prod_id");

        txtProdId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdIdActionPerformed(evt);
            }
        });

        rbtnMobile.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnMobile);
        rbtnMobile.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        rbtnMobile.setForeground(new java.awt.Color(194, 1, 20));
        rbtnMobile.setText("Mobile");
        rbtnMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMobileActionPerformed(evt);
            }
        });

        rbtnAccessories.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnAccessories);
        rbtnAccessories.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        rbtnAccessories.setForeground(new java.awt.Color(194, 1, 20));
        rbtnAccessories.setText("Accessories");
        rbtnAccessories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAccessoriesActionPerformed(evt);
            }
        });

        txtProdName.setFont(new java.awt.Font("Gill Sans MT", 0, 25)); // NOI18N
        txtProdName.setBorder(null);
        txtProdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProdQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                            .addComponent(lblProdName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProdPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProdType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProdPrice)
                            .addComponent(jSeparator1)
                            .addComponent(txtProdQuantity)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator2)
                            .addComponent(lblProdBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblProdId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtProdId))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rbtnMobile)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtnAccessories)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtProdBrand)
                            .addComponent(jSeparator5))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtProdName)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProdName)
                .addGap(4, 4, 4)
                .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblProdPrice)
                .addGap(3, 3, 3)
                .addComponent(txtProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblProdQuantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProdQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProdType)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnMobile)
                    .addComponent(rbtnAccessories))
                .addGap(12, 12, 12)
                .addComponent(lblProdBrand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProdBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblProdId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProdId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableProductData.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        jTableProductData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProductData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProductData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE product SET prod_name = ?,prod_price = ?, prod_quantity = ?, prod_type = ?,"
            + "prod_brand = ? WHERE prod_id = ?";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, txtProdName.getText());
            preparedStatement.setInt(2, Integer.parseInt(txtProdPrice.getText()));
            preparedStatement.setInt(3, Integer.parseInt(txtProdQuantity.getText()));
            preparedStatement.setString(4, type);
            preparedStatement.setString(5, txtProdBrand.getText());
            preparedStatement.setInt(6, Integer.parseInt(txtProdId.getText()));
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null,"Record Updated Successfully");
            updatejProductTableData(AddProductPanel.sql);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO product(prod_name,prod_price,prod_quantity,prod_type,prod_brand)"
            + "VALUES(?, ?, ?, ?, ?)";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, txtProdName.getText());
            preparedStatement.setInt(2, Integer.parseInt(txtProdPrice.getText()));
            preparedStatement.setInt(3, Integer.parseInt(txtProdQuantity.getText()));
            preparedStatement.setString(4, type);
            preparedStatement.setString(5, txtProdBrand.getText());
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null,"Product Added Successfully");
            updatejProductTableData(AddProductPanel.sql);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Issue"+e.getMessage());
        }
        finally{
                txtProdId.setText("");
                txtProdName.setText("");
                txtProdPrice.setText("");
                txtProdQuantity.setText("");
                txtProdBrand.setText("");
            }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if("".equals(txtProdId.getText())){
            JOptionPane.showMessageDialog(null,"Please select record to delete");
        }
        else{
            int btn = JOptionPane.showConfirmDialog(null,"Are you sure you wanna delete the record?","Delete",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(btn == JOptionPane.YES_OPTION){
                try{
                    String sql = "DELETE FROM product WHERE prod_id = ?";
                    preparedStatement = conn.prepareStatement(sql);
                    preparedStatement.setInt(1, Integer.parseInt(txtProdId.getText()));
                    preparedStatement.execute();
                    JOptionPane.showMessageDialog(null,"Record Deleted Successfully!");
                    updatejProductTableData(AddProductPanel.sql);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Issue:"+e.getMessage());
                }
                finally{
                    try{
                        preparedStatement.close();
                    }
                    catch(Exception e){}
                }
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtProdPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdPriceActionPerformed

    private void txtProdQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdQuantityActionPerformed

    private void txtProdBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdBrandActionPerformed

    private void txtProdIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdIdActionPerformed

    private void rbtnAccessoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAccessoriesActionPerformed
        // TODO add your handling code here:
        type = "Accessories";
    }//GEN-LAST:event_rbtnAccessoriesActionPerformed

    private void jTableProductDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductDataMouseClicked
        // TODO add your handling code here:
        int selectedRow = jTableProductData.getSelectedRow();
        String selectedPId = jTableProductData.getModel().getValueAt(selectedRow, 0).toString();
        try{
            String sql = "SELECT * FROM product WHERE prod_id = " + selectedPId;
            preparedStatement = conn.prepareStatement(sql);
            rs = preparedStatement.executeQuery();
            if(rs.next()){
                txtProdId.setText(rs.getString("prod_id"));
                txtProdName.setText(rs.getString("prod_name"));
                txtProdPrice.setText(rs.getString("prod_price"));
                txtProdQuantity.setText(rs.getString("prod_quantity"));
                String typeSelected = rs.getString("prod_type");
                if("Mobile".equals(typeSelected)){
                    type = "Mobile";
                    rbtnMobile.setSelected(true);
                }
                else{
                    type = "Accessories";
                    rbtnAccessories.setSelected(true);
                }
                txtProdBrand.setText(rs.getString("prod_brand"));
            }
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_jTableProductDataMouseClicked

    private void txtProdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdNameActionPerformed

    private void rbtnMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMobileActionPerformed
        // TODO add your handling code here:
        type = "Mobile";
    }//GEN-LAST:event_rbtnMobileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTableProductData;
    private javax.swing.JLabel lblProdBrand;
    private javax.swing.JLabel lblProdId;
    private javax.swing.JLabel lblProdName;
    private javax.swing.JLabel lblProdPrice;
    private javax.swing.JLabel lblProdQuantity;
    private javax.swing.JLabel lblProdType;
    private javax.swing.JRadioButton rbtnAccessories;
    private javax.swing.JRadioButton rbtnMobile;
    private javax.swing.JTextField txtProdBrand;
    private javax.swing.JTextField txtProdId;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtProdPrice;
    private javax.swing.JTextField txtProdQuantity;
    // End of variables declaration//GEN-END:variables
    private String type = null;
    static final String sql;
    
}
